<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Webit\\Util\\EvalMath\\' => array($vendorDir . '/webit/eval-math/src'),
    'Syrnik\\' => array($vendorDir . '/syrnik/wa-shipping-utils/src'),
    'SergeR\\CakeUtility\\' => array($vendorDir . '/serger/cake-utility/src'),
    'SergeR\\' => array($vendorDir . '/serger/process-logger/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
);
