<?php return array(
    'root' => array(
        'name' => 'syrnik/shipping-dostavist',
        'pretty_version' => 'dev-develop',
        'version' => 'dev-develop',
        'reference' => '0051a43b4414cb5850b44a6c4f7995fdc696c0bf',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'psr/log' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '4ebe3a8bf773a19edfe0a84b6585ba3d401b724d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'serger/cake-utility' => array(
            'pretty_version' => 'v1.0.3',
            'version' => '1.0.3.0',
            'reference' => '05ff0b5679bc1d07a7110decab8db37bc72ebdc8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../serger/cake-utility',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'serger/eval-math' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'a9eae61df21bd19f693f78261f40a705f0551232',
            'type' => 'library',
            'install_path' => __DIR__ . '/../serger/eval-math',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'serger/process-logger' => array(
            'pretty_version' => 'v1.1.3',
            'version' => '1.1.3.0',
            'reference' => 'eb1b94b23d182d375e53261eb88b9bc039f56c5d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../serger/process-logger',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'syrnik/shipping-dostavist' => array(
            'pretty_version' => 'dev-develop',
            'version' => 'dev-develop',
            'reference' => '0051a43b4414cb5850b44a6c4f7995fdc696c0bf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'syrnik/wa-shipping-utils' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => '700532e6cf208c673129e29bd10648e822ed8b27',
            'type' => 'library',
            'install_path' => __DIR__ . '/../syrnik/wa-shipping-utils',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webit/eval-math' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '0e7c3a1e0f536b826f04553726c112996b52ded6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webit/eval-math',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
