<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2c3dc3adcdb035488e68a9fa8ebea13a
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Syrnik\\' => 7,
            'SergeR\\Util\\EvalMath\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Syrnik\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/src',
        ),
        'SergeR\\Util\\EvalMath\\' => 
        array (
            0 => __DIR__ . '/..' . '/serger/eval-math/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2c3dc3adcdb035488e68a9fa8ebea13a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2c3dc3adcdb035488e68a9fa8ebea13a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit2c3dc3adcdb035488e68a9fa8ebea13a::$classMap;

        }, null, ClassLoader::class);
    }
}
